#!/bin/bash

# Check if local file exists, if not, create it
if [ ! -f local ]; then
    touch local
fi

# Check if config file exists, if not, create it
if [ ! -f config ]; then
    touch config
fi

# Retrieve specified files from ~/.local/
mkdir -p local
cp ~/.local/src local/ -r
cp ~/.local/bin local/ -r
cp ~/.local/share/bg local/share
cp ~/.local/share/larbs local/share

# Retrieve specified files from ~/.config/
mkdir -p config
cp ~/.config/mpv config/
cp ~/.config/ncmpcpp config/
cp ~/.config/nvim config/
cp ~/.config/pinentry config/
cp ~/.config/pipewire config/
cp ~/.config/pulse config/
cp ~/.config/python config/
cp ~/.config/shell config/
cp ~/.config/wal config/
cp ~/.config/wget config/
cp ~/.config/x11 config/
cp ~/.config/zathura config/

# Add changes to git
git add local config

# Make a git commit
git commit -m "Updated local and config files"

# Push changes to remote repository
git push origin master
